
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrhuynyipwcgrdligbhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyaHV5bnlpcHdjZ3JkbGlnYmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzMDIyOTYsImV4cCI6MjA1NDg3ODI5Nn0.N973A98oFmZkC4t2oULlVj9bv7hUuIjR6O7zN_ojgZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
